// Cambridge-aligned 22-week topic sequences for all subjects
// Each subject × grade maps week_number → topic string

type SubjectCode = "PHY" | "MAT" | "CHE" | "BIO" | "ECO"
type GradeSequences = Record<number, Record<number, string>>

export const SUBJECT_GRADE_SEQUENCES: Record<SubjectCode, GradeSequences> = {
  PHY: {} as GradeSequences, // Already in getGradeSequence()
  MAT: {
    7: {
      1: "Integers and Place Value",
      2: "Factors, Multiples and Primes",
      3: "Fractions and Decimals",
      4: "Percentages",
      5: "Ratio and Proportion",
      6: "Algebra: Expressions and Substitution",
      7: "Algebra: Linear Equations",
      8: "Geometry: Angles and Constructions",
      9: "Geometry: Triangles and Quadrilaterals",
      10: "Perimeter and Area",
      11: "Volume and Surface Area",
      12: "Statistics: Data Collection and Charts",
      13: "Statistics: Mean, Median, Mode",
      14: "Probability: Introduction",
      15: "Negative Numbers",
      16: "Indices and Standard Form",
      17: "Sequences and Patterns",
      18: "Functions and Graphs",
      19: "Transformations",
      20: "Pythagoras' Theorem",
      21: "Review: Number and Algebra",
      22: "End of Year Assessment",
    },
    8: {
      1: "Number: Powers and Roots",
      2: "Fractions, Decimals and Percentages Review",
      3: "Ratio and Proportion Applications",
      4: "Algebra: Expanding and Factorising",
      5: "Algebra: Linear Inequalities",
      6: "Simultaneous Equations",
      7: "Algebra: Quadratic Expressions",
      8: "Geometry: Circle Properties",
      9: "Geometry: Congruence and Similarity",
      10: "Area and Volume of Prisms",
      11: "Trigonometry: Right-Angled Triangles",
      12: "Statistics: Scatter Diagrams and Correlation",
      13: "Probability: Combined Events",
      14: "Sets and Venn Diagrams",
      15: "Number: Standard Form",
      16: "Direct and Inverse Proportion",
      17: "Algebraic Fractions",
      18: "Graphs of Linear Functions",
      19: "Graphs of Quadratic Functions",
      20: "Vectors and Matrices",
      21: "Transformations Review",
      22: "End of Year Assessment",
    },
    9: {
      1: "Number: Surds and Indices",
      2: "Algebra: Quadratic Equations",
      3: "Algebra: Completing the Square",
      4: "Algebra: Algebraic Fractions",
      5: "Functions and Notation",
      6: "Coordinate Geometry",
      7: "Geometry: Circle Theorems",
      8: "Geometry: Angles in Polygons",
      9: "Mensuration: Arc Length and Sector Area",
      10: "Mensuration: Volume of Pyramids and Cones",
      11: "Trigonometry: Sine and Cosine Rules",
      12: "Trigonometry: 3D Problems",
      13: "Statistics: Cumulative Frequency",
      14: "Statistics: Histograms",
      15: "Probability: Conditional Probability",
      16: "Sequences: Arithmetic and Geometric",
      17: "Graphs: Exponential and Trigonometric",
      18: "Graphs: Transformations of Functions",
      19: "Differentiation: Introduction",
      20: "Integration: Introduction",
      21: "IGCSE Past Paper Practice",
      22: "IGCSE Mock Examination",
    },
    10: {
      1: "Number: Bounds and Error Intervals",
      2: "Algebra: Factor Theorem",
      3: "Algebra: Algebraic Proof",
      4: "Algebra: Solving Quadratic Inequalities",
      5: "Algebra: Simultaneous Equations (Non-Linear)",
      6: "Coordinate Geometry of Circles",
      7: "Geometry: Congruence and Similarity Proofs",
      8: "Geometry: Area of Triangles (1/2 ab sin C)",
      9: "Trigonometry: Graphs of Trigonometric Functions",
      10: "Trigonometry: Trigonometric Identities",
      11: "Vectors: Magnitude and Direction",
      12: "Vectors: Geometric Proofs",
      13: "Transformations: Combined Transformations",
      14: "Statistics: Probability Distributions",
      15: "Sets: Set Notation and Probability",
      16: "Differentiation: Stationary Points",
      17: "Differentiation: Applications",
      18: "Integration: Definite Integrals",
      19: "Integration: Area Under a Curve",
      20: "Rate of Change and Kinematics",
      21: "IGCSE Extended Past Papers",
      22: "IGCSE Final Review",
    },
    11: {
      1: "Algebra: Modulus Functions",
      2: "Algebra: Partial Fractions",
      3: "Algebra: Binomial Expansion",
      4: "Coordinate Geometry: Equation of a Circle",
      5: "Trigonometry: Radians",
      6: "Trigonometry: Sec, Cosec, Cot",
      7: "Trigonometry: Compound Angle Formulae",
      8: "Differentiation: Chain, Product, Quotient Rules",
      9: "Differentiation: Parametric Equations",
      10: "Integration: Integration by Substitution",
      11: "Integration: Integration by Parts",
      12: "Numerical Methods: Iteration",
      13: "Numerical Methods: Newton-Raphson",
      14: "Vectors: 3D Vectors",
      15: "Vectors: Dot Product",
      16: "Exponentials and Logarithms",
      17: "Exponential Growth and Decay",
      18: "Statistics: Normal Distribution",
      19: "Statistics: Sampling",
      20: "Probability: Discrete Random Variables",
      21: "Hypothesis Testing",
      22: "AS Level Review",
    },
    12: {
      1: "Proof by Contradiction",
      2: "Rational Functions and Graphs",
      3: "Further Algebra: Summation",
      4: "Further Trigonometry: Inverse Functions",
      5: "Further Trigonometry: Double Angle Formulae",
      6: "Further Differentiation: Implicit",
      7: "Further Differentiation: Differential Equations",
      8: "Further Integration: Reduction Formulae",
      9: "Further Integration: Improper Integrals",
      10: "Numerical Methods: Differential Equations",
      11: "Vectors: Cross Product",
      12: "Vectors: Equations of Planes",
      13: "Complex Numbers: Argand Diagram",
      14: "Complex Numbers: De Moivre's Theorem",
      15: "Complex Numbers: Roots of Unity",
      16: "Probability: Continuous Random Variables",
      17: "Statistics: Poisson Distribution",
      18: "Hypothesis Testing: Chi-Squared",
      19: "Mechanics: Kinematics in 2D",
      20: "Mechanics: Projectiles",
      21: "A Level Past Papers",
      22: "A Level Final Review",
    },
  },
  CHE: {
    7: {
      1: "Introduction to Chemistry: Lab Safety",
      2: "States of Matter: Particle Theory",
      3: "Changes of State",
      4: "Elements, Compounds, and Mixtures",
      5: "Separation Techniques: Filtration and Evaporation",
      6: "Separation Techniques: Distillation and Chromatography",
      7: "Atoms and Elements: Periodic Table Introduction",
      8: "Metals and Non-Metals",
      9: "Chemical Reactions: Signs of a Reaction",
      10: "Acids and Alkalis: pH Scale",
      11: "Neutralisation Reactions",
      12: "Chemical Equations: Word Equations",
      13: "The Air and Atmosphere",
      14: "Oxygen and Combustion",
      15: "Rusting and Corrosion",
      16: "Rocks and Soil Formation",
      17: "The Rock Cycle",
      18: "Fuels and Energy",
      19: "Water: Properties and Treatment",
      20: "Solutions and Solubility",
      21: "Review of Key Concepts",
      22: "End of Year Assessment",
    },
    8: {
      1: "Atomic Structure: Protons, Neutrons, Electrons",
      2: "Electron Configuration",
      3: "Ionic Bonding",
      4: "Covalent Bonding",
      5: "Metallic Bonding",
      6: "Chemical Formulae: Writing and Naming",
      7: "Relative Atomic Mass",
      8: "Moles: Introduction",
      9: "Chemical Equations: Balancing",
      10: "Reactivity Series of Metals",
      11: "Displacement Reactions",
      12: "Extraction of Metals",
      13: "Thermal Decomposition",
      14: "Exothermic and Endothermic Reactions",
      15: "Rate of Reaction: Factors",
      16: "Catalysts",
      17: "Salts: Solubility Rules",
      18: "Making Salts: Precipitation",
      19: "pH and Indicators Review",
      20: "Acids, Bases and Carbonates",
      21: "Review: Bonding and Reactions",
      22: "End of Year Assessment",
    },
    9: {
      1: "Atomic Structure: Isotopes",
      2: "Electronic Configuration (Subshells)",
      3: "Ionic and Covalent Bonding Review",
      4: "Giant Covalent Structures",
      5: "Metallic Bonding and Properties",
      6: "Stoichiometry: Moles and Mass",
      7: "Stoichiometry: Limiting Reactants",
      8: "Concentration and Volumetric Analysis",
      9: "Gas Volumes and Molar Volume",
      10: "Redox Reactions: Oxidation States",
      11: "Electrolysis: Principles",
      12: "Electrolysis of Molten Compounds",
      13: "Electrolysis of Aqueous Solutions",
      14: "Periodic Trends: Group 1",
      15: "Group 7: Halogens",
      16: "Transition Metals",
      17: "Energy Changes: Bond Energies",
      18: "Rates of Reaction: Collision Theory",
      19: "Reversible Reactions and Equilibrium",
      20: "Organic Chemistry: Hydrocarbons",
      21: "IGCSE Core Past Papers",
      22: "IGCSE Core Review",
    },
    10: {
      1: "Atomic Structure: Electron Configuration Revisited",
      2: "Periodicity: Period 3 Elements",
      3: "Chemical Bonding: Shapes of Molecules",
      4: "Stoichiometry: Empirical and Molecular Formulae",
      5: "Stoichiometry: Percentage Yield and Purity",
      6: "Chemical Energetics: Enthalpy Change",
      7: "Hess's Law and Enthalpy Cycles",
      8: "Reaction Kinetics: Rate Equations",
      9: "Catalysis: Homogeneous and Heterogeneous",
      10: "Equilibrium: Le Chatelier's Principle",
      11: "Equilibrium Constant Kc",
      12: "Acids and Bases: Strong and Weak",
      13: "pH Calculations",
      14: "Redox Reactions: Half-Equations",
      15: "Electrochemistry: Cell Potentials",
      16: "Group 2: Alkaline Earth Metals",
      17: "Group 17: Halogens and Disproportionation",
      18: "Nitrogen and Sulfur Chemistry",
      19: "Organic Chemistry: Alkanes and Alkenes",
      20: "Organic Chemistry: Alcohols and Carboxylic Acids",
      21: "IGCSE Extended Past Papers",
      22: "IGCSE Final Review",
    },
    11: {
      1: "Atomic Structure: Ionisation Energy",
      2: "Electron Configuration: Orbitals and Subshells",
      3: "Periodicity: Trends Across Period 3",
      4: "Chemical Bonding: Sigma and Pi Bonds",
      5: "Intermolecular Forces: Van der Waals and Hydrogen Bonding",
      6: "Stoichiometry: Mole Calculations",
      7: "Energetics: Calorimetry",
      8: "Energetics: Born-Haber Cycles",
      9: "Kinetics: Maxwell-Boltzmann Distribution",
      10: "Kinetics: Activation Energy",
      11: "Equilibrium: Kc and Kp",
      12: "Equilibrium: Industrial Applications",
      13: "Acids and Bases: pH of Weak Acids",
      14: "Acid-Base Titrations and Indicators",
      15: "Redox: Electrode Potentials",
      16: "Electrochemistry: Fuel Cells",
      17: "Group 2 and Group 7: Revisited",
      18: "Period 3 Oxides and Chlorides",
      19: "Organic: Introduction to Isomerism",
      20: "Organic: Alkanes and Halogenoalkanes",
      21: "Organic: Alkenes and Alcohols",
      22: "AS Level Review",
    },
    12: {
      1: "Spectroscopy: Mass Spectrometry",
      2: "Spectroscopy: IR and NMR",
      3: "Thermodynamics: Entropy and Free Energy",
      4: "Thermodynamics: Gibbs Free Energy Applications",
      5: "Kinetics: Rate-Determining Step",
      6: "Kinetics: Arrhenius Equation",
      7: "Equilibrium: Acid-Base Equilibria",
      8: "Equilibrium: Buffer Solutions",
      9: "Equilibrium: Solubility Product Ksp",
      10: "Redox: Electrochemical Cells",
      11: "Redox: Nernst Equation",
      12: "Transition Metals: Complex Ion Formation",
      13: "Transition Metals: Ligand Substitution",
      14: "Organic: Chirality and Optical Isomerism",
      15: "Organic: Carbonyl Compounds",
      16: "Organic: Carboxylic Acids and Esters",
      17: "Organic: Amines and Amino Acids",
      18: "Organic: Polymers and Polymerisation",
      19: "Organic: Aromatic Chemistry",
      20: "Organic: Synthesis Routes",
      21: "A Level Past Papers",
      22: "A Level Final Review",
    },
  },
  BIO: {
    7: {
      1: "Introduction to Biology: Characteristics of Life",
      2: "Cells: Animal and Plant Cells",
      3: "Cells: Specialised Cells and Tissues",
      4: "Microscopy: Using a Microscope",
      5: "Classification: Living Things",
      6: "Classification: Vertebrates and Invertebrates",
      7: "Classification: Plants and Fungi",
      8: "Nutrition: Balanced Diet",
      9: "Digestion: The Digestive System",
      10: "Transport: Circulatory System",
      11: "Transport: Blood and Blood Vessels",
      12: "Respiration: Aerobic and Anaerobic",
      13: "Excretion: The Excretory System",
      14: "Sensitivity: Nervous System",
      15: "Reproduction: Plant Reproduction",
      16: "Reproduction: Human Reproductive System",
      17: "Growth and Development",
      18: "Ecology: Habitats and Adaptations",
      19: "Ecology: Food Chains and Webs",
      20: "Ecology: Environmental Change",
      21: "Review: Body Systems",
      22: "End of Year Assessment",
    },
    8: {
      1: "Cells: Diffusion and Osmosis",
      2: "Cells: Active Transport",
      3: "Enzymes: Structure and Function",
      4: "Enzymes: Factors Affecting Rate",
      5: "Photosynthesis: Process and Equation",
      6: "Photosynthesis: Factors Affecting Rate",
      7: "Plant Nutrition: Mineral Requirements",
      8: "Plant Transport: Xylem and Phloem",
      9: "Transpiration and Water Movement",
      10: "Gas Exchange in Plants",
      11: "Human Gas Exchange: The Lungs",
      12: "Human Nutrition: Teeth and Digestion",
      13: "Human Nutrition: Absorption and Assimilation",
      14: "Human Transport: The Heart",
      15: "Human Transport: Blood Composition",
      16: "Disease: Pathogens and Defence",
      17: "Disease: Immunity and Vaccination",
      18: "Drugs: Medicinal and Recreational",
      19: "Microorganisms: Bacteria and Viruses",
      20: "Biotechnology: Fermentation",
      21: "Review: Plant and Human Biology",
      22: "End of Year Assessment",
    },
    9: {
      1: "Cell Structure: Organelles",
      2: "Cell Structure: Prokaryotes vs Eukaryotes",
      3: "Biological Molecules: Carbohydrates",
      4: "Biological Molecules: Proteins and Lipids",
      5: "Enzymes: Mechanism of Action",
      6: "Enzymes: Industrial Applications",
      7: "Plant Nutrition: Leaf Structure",
      8: "Plant Nutrition: Limiting Factors",
      9: "Animal Nutrition: Digestive System",
      10: "Transport in Plants: Xylem and Phloem",
      11: "Transport in Animals: Heart and Circulation",
      12: "Respiration: Aerobic and Anaerobic",
      13: "Gas Exchange: Humans and Plants",
      14: "Excretion: Kidney Structure",
      15: "Coordination: Nervous System",
      16: "Coordination: Hormones",
      17: "Homeostasis: Temperature Regulation",
      18: "Homeostasis: Blood Glucose",
      19: "Reproduction: Sexual and Asexual",
      20: "Inheritance: Chromosomes and Genes",
      21: "IGCSE Core Past Papers",
      22: "IGCSE Core Review",
    },
    10: {
      1: "Cell Division: Mitosis and Meiosis",
      2: "DNA: Structure and Replication",
      3: "Protein Synthesis: Transcription and Translation",
      4: "Inheritance: Monohybrid Crosses",
      5: "Inheritance: Codominance and Sex Linkage",
      6: "Variation: Continuous and Discontinuous",
      7: "Natural Selection and Evolution",
      8: "Selective Breeding",
      9: "Genetic Engineering",
      10: "Biotechnology: Enzymes in Industry",
      11: "Ecology: Ecosystems and Biomes",
      12: "Ecology: Nutrient Cycles",
      13: "Ecology: Carbon and Nitrogen Cycles",
      14: "Human Impact: Pollution",
      15: "Human Impact: Conservation",
      16: "Human Impact: Climate Change",
      17: "Plant Physiology: Tropisms",
      18: "Plant Physiology: Growth Regulators",
      19: "Disease: Immune System",
      20: "Disease: Monoclonal Antibodies",
      21: "IGCSE Extended Past Papers",
      22: "IGCSE Final Review",
    },
    11: {
      1: "Cell Structure: Electron Microscopy",
      2: "Biological Molecules: Testing",
      3: "Enzymes: Inhibitors",
      4: "Cell Membranes: Structure and Transport",
      5: "Cell Division: Cell Cycle and Mitosis",
      6: "DNA: Replication and Repair",
      7: "Protein Synthesis: Detailed Mechanisms",
      8: "Genetic Technology: PCR and Electrophoresis",
      9: "Genetic Technology: Gene Therapy",
      10: "Transport in Animals: Cardiac Cycle",
      11: "Transport in Plants: Transpiration Pull",
      12: "Gas Exchange: Control of Breathing",
      13: "Excretion: Kidney Function and Regulation",
      14: "Homeostasis: Thermoregulation",
      15: "Coordination: Synaptic Transmission",
      16: "Coordination: Endocrine System",
      17: "Immunity: Immune Response",
      18: "Immunity: Vaccination",
      19: "Infectious Disease: HIV and Malaria",
      20: "Infectious Disease: Antibiotic Resistance",
      21: "Ecology: Population Dynamics",
      22: "AS Level Review",
    },
    12: {
      1: "Photosynthesis: Light-Dependent Reactions",
      2: "Photosynthesis: Calvin Cycle",
      3: "Respiration: Glycolysis and Krebs Cycle",
      4: "Respiration: Oxidative Phosphorylation",
      5: "Energy Transfer: Ecosystems",
      6: "Nutrient Cycles: Detailed",
      7: "Inheritance: Dihybrid Crosses",
      8: "Inheritance: Linkage and Gene Mapping",
      9: "Evolution: Hardy-Weinberg Principle",
      10: "Evolution: Speciation",
      11: "Genetic Control: Gene Regulation",
      12: "Genetic Control: Epigenetics",
      13: "Biotechnology: Recombinant DNA",
      14: "Biotechnology: DNA Sequencing",
      15: "Bioethics: Genetic Screening",
      16: "Nervous System: Action Potentials",
      17: "Nervous System: Synaptic Transmission",
      18: "Muscle: Structure and Contraction",
      19: "Hormones: Adrenal and Pancreatic",
      20: "Reproduction: Hormonal Control",
      21: "A Level Past Papers",
      22: "A Level Final Review",
    },
  },
  ECO: {
    7: {
      1: "Introduction to Economics: Scarcity and Choice",
      2: "Needs and Wants",
      3: "Resources: Natural, Human and Capital",
      4: "Opportunity Cost",
      5: "Specialisation and Division of Labour",
      6: "Production: Goods and Services",
      7: "Markets: Buyers and Sellers",
      8: "Money and Its Functions",
      9: "Banks and Saving",
      10: "Income and Expenditure",
      11: "Consumption and Saving",
      12: "Demand and Supply: Basic Concepts",
      13: "Price Determination",
      14: "Competition in Markets",
      15: "Labour Markets: Wages",
      16: "Government: Services Provided",
      17: "Taxation: Basic Principles",
      18: "Trade: Local and Regional",
      19: "Global Trade: Exports and Imports",
      20: "Economic Development: Introduction",
      21: "Review of Key Concepts",
      22: "End of Year Assessment",
    },
    8: {
      1: "Demand: Law of Demand",
      2: "Supply: Law of Supply",
      3: "Market Equilibrium: Price Mechanism",
      4: "Price Elasticity of Demand",
      5: "Price Elasticity of Supply",
      6: "Production: Costs and Revenue",
      7: "Economies of Scale",
      8: "Market Structures: Competition vs Monopoly",
      9: "Labour Market: Demand for Labour",
      10: "Labour Market: Supply of Labour",
      11: "Trade Unions",
      12: "Government: Public Expenditure",
      13: "Taxation: Direct and Indirect",
      14: "Gross Domestic Product (GDP)",
      15: "Inflation: Causes and Effects",
      16: "Unemployment: Types and Causes",
      17: "International Trade: Comparative Advantage",
      18: "Protectionism: Tariffs and Quotas",
      19: "Exchange Rates",
      20: "Balance of Payments",
      21: "Review: Micro and Macro Basics",
      22: "End of Year Assessment",
    },
    9: {
      1: "Demand: Determinants Revisited",
      2: "Supply: Determinants Revisited",
      3: "Market Equilibrium: Changes",
      4: "Elasticity: Cross and Income",
      5: "Production: Short Run vs Long Run",
      6: "Costs: Fixed, Variable and Total",
      7: "Revenue: Total, Average and Marginal",
      8: "Profit: Normal and Abnormal",
      9: "Market Structures: Perfect Competition",
      10: "Market Structures: Monopoly",
      11: "Market Failure: Externalities",
      12: "Market Failure: Public Goods",
      13: "Government Intervention: Taxes and Subsidies",
      14: "Aggregate Demand: Components",
      15: "Aggregate Supply: Short Run and Long Run",
      16: "Macroeconomic Equilibrium",
      17: "Economic Growth: Causes and Benefits",
      18: "Inflation: Demand-Pull and Cost-Push",
      19: "Unemployment: Cyclical and Structural",
      20: "Fiscal Policy: Government Budget",
      21: "IGCSE Core Past Papers",
      22: "IGCSE Core Review",
    },
    10: {
      1: "Demand: PED Calculations and Applications",
      2: "Supply: PES Calculations",
      3: "Market Equilibrium: Consumer and Producer Surplus",
      4: "Labour Market: Wage Determination",
      5: "Labour Market: Discrimination and Inequality",
      6: "Market Structures: Monopolistic Competition",
      7: "Market Structures: Oligopoly",
      8: "Market Failure: Merit and Demerit Goods",
      9: "Market Failure: Environmental Externalities",
      10: "Government Intervention: Price Controls",
      11: "Government Failure",
      12: "Aggregate Demand: Consumption and Investment",
      13: "Aggregate Demand: Government and Net Exports",
      14: "Aggregate Supply: Determinants",
      15: "Macroeconomic Equilibrium: AD-AS Model",
      16: "Economic Growth: Policies",
      17: "Inflation: Consequences and Policies",
      18: "Unemployment: Policies to Reduce",
      19: "Monetary Policy: Interest Rates",
      20: "Supply-Side Policies",
      21: "IGCSE Extended Past Papers",
      22: "IGCSE Final Review",
    },
    11: {
      1: "Scarcity, Choice and Opportunity Cost Revisited",
      2: "Demand and Supply: Elasticities Revisited",
      3: "Indifference Curves and Budget Lines",
      4: "Costs and Revenue: Detailed Analysis",
      5: "Profit Maximisation: Marginal Approach",
      6: "Perfect Competition: Short Run and Long Run",
      7: "Monopoly: Price and Output Decisions",
      8: "Monopoly: Price Discrimination",
      9: "Oligopoly: Game Theory",
      10: "Labour Market: Marginal Revenue Product",
      11: "Wage Determination: Monopsony",
      12: "Market Failure: Information Gaps",
      13: "Government Intervention: Cost-Benefit Analysis",
      14: "Aggregate Demand: Consumption Function",
      15: "Aggregate Demand: Multiplier Effect",
      16: "Aggregate Supply: Keynesian vs Classical",
      17: "Macroeconomic Policy: Objectives",
      18: "Fiscal Policy: Government Spending",
      19: "Monetary Policy: Money Supply",
      20: "Exchange Rates: Determination",
      21: "Balance of Payments: Current Account",
      22: "AS Level Review",
    },
    12: {
      1: "Production and Cost Functions in the Long Run",
      2: "Profit Maximisation: Alternative Objectives",
      3: "Perfect Competition: Dynamic Efficiency",
      4: "Monopoly: Natural Monopoly Regulation",
      5: "Oligopoly: Collusion and Cartels",
      6: "Contestable Markets",
      7: "Labour Market: Human Capital",
      8: "Labour Market: Minimum Wage Debates",
      9: "Labour Market: Trade Union Power",
      10: "Economic Inequality: Lorenz Curve and Gini",
      11: "Poverty: Absolute and Relative",
      12: "Government: Redistribution Policies",
      13: "Macroeconomic Policy: Policy Conflicts",
      14: "Economic Growth: Sustainable Growth",
      15: "Economic Cycle: Phases and Indicators",
      16: "Inflation: Phillips Curve",
      17: "Unemployment: Natural Rate Hypothesis",
      18: "International Trade: Terms of Trade",
      19: "Exchange Rates: Fixed vs Floating",
      20: "Economic Development: Indicators and Strategies",
      21: "A Level Past Papers",
      22: "A Level Final Review",
    },
  },
}

export function getSubjectTopic(subject: SubjectCode, grade: number, week: number): string {
  if (subject === "PHY") return "" // PHY handled by getGradeSequence
  const gradeData = SUBJECT_GRADE_SEQUENCES[subject]?.[grade]
  if (!gradeData) return ""
  return gradeData[week] ?? ""
}

export const SUBJECTS_WITH_TEMPLATES: SubjectCode[] = ["PHY", "MAT", "CHE", "BIO", "ECO"]
