import { NextRequest, NextResponse } from "next/server"
import { createServerSupabaseClient } from "@/lib/supabase/server"

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params
    const supabase = await createServerSupabaseClient()

    const { data: plan } = await (supabase.from("syllabus_planning") as any)
      .select("*, topics:syllabus_topics!inner(*)")
      .eq("id", id)
      .single()

    if (!plan) return new NextResponse("Syllabus not found", { status: 404 })

    const grade = plan.grade
    const week = plan.week_number
    const dateStr = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })
    const dateCode = new Date().toISOString().split("T")[0].replace(/-/g, "")

    const esc = (s: string) => (s || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")

    const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Syllabus - Grade ${grade} Week ${week}</title>
<script src="https://cdn.tailwindcss.com"></script>
<style>
body{font-family:'Segoe UI',system-ui,sans-serif;font-size:14px}
@media print{body{background:#fff;padding:0}.no-print{display:none!important}}
canvas{touch-action:none;cursor:crosshair;border-radius:8px;max-width:100%}
.signature-box{border:2px dashed #ccc;border-radius:12px;min-height:120px}
</style>
</head>
<body class="bg-gray-50 text-gray-900 p-4 md:p-8 min-h-screen">
<div class="max-w-5xl mx-auto" id="syllabus-content">
<div class="bg-white rounded-2xl shadow-sm border p-6 md:p-10 space-y-8">

<div class="border-b pb-6 flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
<div>
<h1 class="text-2xl md:text-3xl font-bold">Syllabus Plan</h1>
<p class="text-gray-500 mt-1">Grade ${grade} · Week ${week} · ${dateStr}</p>
<p class="text-gray-700 mt-2 font-medium text-lg">Topic: ${esc(plan.topic)}</p>
</div>
<div class="shrink-0 text-center">
<img src="https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=${encodeURIComponent(`https://physics-command-center.vercel.app/syllabus/public/${id}`)}" alt="QR" class="w-24 h-24 mx-auto rounded border" />
<p class="text-[10px] text-gray-400 mt-1">Scan to view online</p>
</div>
</div>

<div class="bg-gray-50 rounded-xl p-4 md:p-6 space-y-4 border">
<h3 class="font-semibold text-gray-700">Student Information</h3>
<div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
<div><label class="block text-sm font-medium text-gray-600 mb-1">Full Name</label>
<input id="student-name" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm" placeholder="Enter your name" /></div>
<div><label class="block text-sm font-medium text-gray-600 mb-1">Date</label>
<input type="text" value="${dateCode}" readonly class="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm bg-gray-100 text-gray-500" /></div>
</div>
</div>

<div class="space-y-8 mt-6">
${(plan.topics || []).map((t: any, idx: number) => `
<div class="rounded-xl border p-5 space-y-4">
<div class="flex items-start gap-3">
<div class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-100 text-xs font-bold text-blue-700">${idx + 1}</div>
<div class="flex-1"><p class="font-medium text-gray-800">${esc(t.topic)}</p></div>
</div>
<div class="space-y-3">
<textarea rows="3" class="w-full rounded-lg border border-gray-300 p-3 text-sm resize-y" placeholder="Type your answer here" onpaste="event.preventDefault();alert('Paste disabled')" oncopy="event.preventDefault()" oncut="event.preventDefault()"></textarea>
<canvas id="c${idx}" width="700" height="250" class="w-full rounded-lg border"></canvas>
</div>
</div>`).join("")}
</div>

<div class="rounded-xl border-2 border-dashed border-gray-400 p-6 space-y-3 mt-8">
<h3 class="font-semibold text-gray-700">Signature</h3>
<canvas id="sig" width="700" height="120" class="w-full signature-box"></canvas>
<div class="flex gap-2 no-print">
<button onclick="clearC('sig')" class="px-4 py-2 text-sm border rounded-lg hover:bg-gray-100">Clear</button>
</div>
</div>

<div class="flex flex-wrap gap-3 pt-4 no-print">
<button onclick="window.print()" class="px-6 py-3 bg-blue-600 text-white rounded-xl font-medium hover:bg-blue-700 shadow-sm">Print / Save PDF</button>
<button onclick="clearAll()" class="px-4 py-3 border rounded-xl font-medium hover:bg-gray-100">Clear All</button>
</div>

<div class="border-t pt-6 text-center text-sm text-gray-400">
<p>Generated by Physics Command Center - SHB Modernhill</p>
</div>
</div>
</div>

<script>
const canvases = {}
function initCanvas(id) {
  const c = document.getElementById(id); if(!c) return
  const ctx = c.getContext("2d")
  ctx.fillStyle="#fff"; ctx.fillRect(0,0,c.width,c.height)
  ctx.strokeStyle="#1a1a2e"; ctx.lineWidth=2.5; ctx.lineCap="round"; ctx.lineJoin="round"
  let drawing=false, last=null
  function pos(e) {
    const r=c.getBoundingClientRect(), s=c.width/r.width, sy=c.height/r.height
    const t=e.touches?e.touches[0]:e
    return {x:(t.clientX-r.left)*s,y:(t.clientY-r.top)*sy}
  }
  function start(e){e.preventDefault();drawing=true;const p=pos(e);last=p;ctx.beginPath();ctx.moveTo(p.x,p.y)}
  function move(e){if(!drawing)return;e.preventDefault();const p=pos(e);if(last){ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke()}last=p}
  function stop(){drawing=false;last=null}
  c.addEventListener("mousedown",start);c.addEventListener("mousemove",move);c.addEventListener("mouseup",stop);c.addEventListener("mouseleave",stop)
  c.addEventListener("touchstart",start,{passive:false});c.addEventListener("touchmove",move,{passive:false});c.addEventListener("touchend",stop)
}
function clearC(id){const c=document.getElementById(id);if(!c)return;c.getContext("2d").fillRect(0,0,c.width,c.height)}
function clearAll(){document.querySelectorAll("textarea").forEach(t=>t.value="");document.querySelectorAll("canvas").forEach(c=>clearC(c.id))}
document.addEventListener("DOMContentLoaded",()=>document.querySelectorAll("canvas").forEach(c=>initCanvas(c.id)))
</script>
</body></html>`

    return new NextResponse(html, {
      headers: { "Content-Type": "text/html;charset=utf-8" },
    })
  } catch (error) {
    return new NextResponse("Error loading syllabus", { status: 500 })
  }
}
