import type { AgentInput, BroadcastMessage } from "./agent-types"

function getEmoji(topic: string): string {
  const emojiMap: Record<string, string> = {
    kinematics: "🏃‍♂️",
    forces: "💪",
    energy: "⚡",
    waves: "🌊",
    electricity: "💡",
    magnetism: "🧲",
    thermal: "🔥",
    pressure: "🎈",
    density: "⚖️"
  }
  const key = topic.toLowerCase()
  for (const [k, v] of Object.entries(emojiMap)) {
    if (key.includes(k)) return v
  }
  return "🔬"
}

function getWaBody(topic: string, grade: number, week: number): string {
  const emoji = getEmoji(topic)

  return (
    `*📢 PHYSICS COMMAND CENTER — WEEK ${week} UPDATE*\n\n` +
    `Greetings, Physics Warriors! ${emoji}\n\n` +
    `Ready for an exciting week? We will be exploring *${topic}* in Grade ${grade}!\n\n` +
    `📋 *Weekly Schedule:*\n` +
    `📖 Day 1 — Pre-class review + Entry Ticket + ${topic} Hook Activity\n` +
    `📝 Day 2 — Productive Struggle: Level 2 Worksheet (find the intentional error!)\n` +
    `🧪 Day 3 — Lab Day: hands-on practical session\n` +
    `📚 Day 4 — CER Challenge + Wrap-up\n\n` +
    `🎯 *This Week's Targets:*\n` +
    `✅ Watch pre-class video (link available on LMS)\n` +
    `✅ Complete guided notes\n` +
    `✅ Finish all 3 worksheet levels\n` +
    `✅ Submit Mistake Journal entry\n\n` +
    `💡 *Reminder:* Bring your calculator, ruler, and scientific curiosity!\n\n` +
    `Keep questioning, keep exploring! 🚀\n` +
    `— Physics Department`
  )
}

function getLmsTitle(topic: string, week: number): string {
  return `📦 Week ${week} Package: ${topic} — Flipped Classroom`
}

function getLmsBody(topic: string, grade: number): string {
  return (
    `## 📦 Weekly Physics Package\n\n` +
    `**Grade:** ${grade}\n` +
    `**Topic:** ${topic}\n` +
    `**Model:** Flipped Classroom\n\n` +
    `---\n\n` +
    `### 📺 Pre-Class (Complete BEFORE class)\n\n` +
    `1. Watch the introductory video on ${topic} (link below)\n` +
    `2. Complete the guided notes — fill in the blanks\n` +
    `3. Complete the Entry Ticket Quiz on the LMS (minimum score 2/3 required for lab participation)\n\n` +
    `---\n\n` +
    `### 📝 In-Class Activities\n\n` +
    `**Phase 1 — Entry Ticket & Hook (5 minutes)**\n` +
    `- Entry ticket quiz review\n` +
    `- Hook question challenge\n\n` +
    `**Phase 2 — Productive Struggle (20 minutes)**\n` +
    `- Complete Level 2 Worksheet (group work)\n` +
    `- Identify and correct intentional errors\n` +
    `- Peer grading upon completion\n\n` +
    `**Phase 3 — CER Challenge (10 minutes)**\n` +
    `- Analyse the physics phenomenon\n` +
    `- Write Claim, Evidence, Reasoning\n\n` +
    `**Phase 4 — Wrap-up (5 minutes)**\n` +
    `- Mistake Journal\n` +
    `- Preview of next week's topic\n\n` +
    `---\n\n` +
    `### 📎 Attachments\n\n` +
    `- Worksheet (3 levels) — print or access digitally\n` +
    `- Lab Safety Sheet\n` +
    `- CER Template\n\n` +
    `---\n\n` +
    `*Generated by Physics Command Center — AI-Powered Teaching Platform*`
  )
}

function getParentMessage(topic: string, grade: number): string {
  const emoji = getEmoji(topic)
  return (
    `Dear Parents and Guardians of Grade ${grade} Students,\n\n` +
    `We wish to inform you that this week in Physics class, your child will be studying *${topic}* ${emoji}.\n\n` +
    `The lessons will follow the *Flipped Classroom* model, in which students watch instructional videos and complete guided notes BEFORE attending class. We kindly request your support in the following areas:\n\n` +
    `1. Remind your child to watch the pre-class video available on the LMS platform\n` +
    `2. Ensure they complete the Entry Ticket Quiz before the lesson begins\n` +
    `3. Support their learning at home — ask them what they have discovered!\n\n` +
    `For further information, please check the LMS or contact the subject teacher.\n\n` +
    `Yours sincerely,\n` +
    `Tim Fisika SHB Modernhill`
  )
}

export async function generateBroadcast(input: AgentInput): Promise<BroadcastMessage> {
  const deadline = `Deadline: Friday, 11:59 PM (end of week)`

  return {
    wa_message: getWaBody(input.topic, input.grade, input.week_number),
    lms_post: {
      title: getLmsTitle(input.topic, input.week_number),
      body: getLmsBody(input.topic, input.grade),
      attachments: [
        { name: `Worksheet_${input.topic.replace(/\s+/g, "_")}_G${input.grade}_W${input.week_number}.pdf`, url: "#" },
        { name: `CER_Template_G${input.grade}.pdf`, url: "#" },
        { name: `Lab_Safety_Sheet.pdf`, url: "#" }
      ],
      deadline
    },
    parent_message: getParentMessage(input.topic, input.grade)
  }
}
