import type { AgentInput, BroadcastMessage } from "./agent-types"

function getEmoji(topic: string): string {
  const emojiMap: Record<string, string> = {
    kinematics: "🏃‍♂️",
    forces: "💪",
    energy: "⚡",
    waves: "🌊",
    electricity: "💡",
    magnetism: "🧲",
    thermal: "🔥",
    pressure: "🎈",
    density: "⚖️"
  }
  const key = topic.toLowerCase()
  for (const [k, v] of Object.entries(emojiMap)) {
    if (key.includes(k)) return v
  }
  return "🔬"
}

function getWaBody(topic: string, grade: number, week: number): string {
  const emoji = getEmoji(topic)
  const days = ["Senin", "Selasa", "Rabu", "Kamis", "Jumat"]
  const day = days[week % 5]

  return (
    `*📢 PHYSICS COMMAND CENTER — WEEK ${week} UPDATE*\n\n` +
    `Halo, Physics Warriors! ${emoji}\n\n` +
    `Siap buat minggu ini seru? Kita bakal explore *${topic}* di Grade ${grade}!\n\n` +
    `📋 *Apa aja yang bakal kita lakukan:*\n` +
    `${emoji} *${day}* — Pre-class review + Entry Ticket + ${topic} Hook Activity\n` +
    `📝 *${day}* — Productive Struggle: worksheet level 2 (jangan lupa cari intentional error!)\n` +
    `🧪 *${day}* — Lab Day! Praktikum langsung — siap-siap kotor tangan!\n` +
    `📚 *${day}* — CER Challenge + Wrap-up\n\n` +
    `🎯 *Target Minggu Ini:*\n` +
    `✅ Tonton video pre-class (link di LMS)\n` +
    `✅ Kerjakan guided notes\n` +
    `✅ Selesaikan 3 level worksheet\n` +
    `✅ Submit Mistake Journal\n\n` +
    `💡 *Reminder:* Jangan lupa bawa kalkulator, penggaris, dan semangat!\n\n` +
    `Keep questioning, keep exploring! 🚀\n` +
    `— Mr. Physics Teacher`
  )
}

function getLmsTitle(topic: string, week: number): string {
  return `📦 Week ${week} Package: ${topic} — Flipped Classroom`
}

function getLmsBody(topic: string, grade: number): string {
  return (
    `## 📦 Weekly Physics Package\n\n` +
    `**Grade:** ${grade}\n` +
    `**Topic:** ${topic}\n` +
    `**Model:** Flipped Classroom\n\n` +
    `---\n\n` +
    `### 📺 Pre-Class (Kerjakan SEBELUM kelas)\n\n` +
    `1. Tonton video pengantar ${topic} (link di bawah)\n` +
    `2. Kerjakan guided notes — isi bagian yang kosong\n` +
    `3. Selesaikan Entry Ticket Quiz di LMS (minimal skor 2/3 untuk bisa ikut sesi lab)\n\n` +
    `---\n\n` +
    `### 📝 In-Class Activities\n\n` +
    `**Phase 1 — Entry Ticket & Hook (5 menit)**\n` +
    `- Entry ticket quiz review\n` +
    `- Hook question challenge\n\n` +
    `**Phase 2 — Productive Struggle (20 menit)**\n` +
    `- Kerjakan Level 2 Worksheet (kelompok)\n` +
    `- Temukan dan perbaiki intentional error\n` +
    `- Peer grading setelah selesai\n\n` +
    `**Phase 3 — CER Challenge (10 menit)**\n` +
    `- Analisis fenomena fisika\n` +
    `- Tulis Claim, Evidence, Reasoning\n\n` +
    `**Phase 4 — Wrap-up (5 menit)**\n` +
    `- Mistake Journal\n` +
    `- Preview minggu depan\n\n` +
    `---\n\n` +
    `### 📎 Attachments\n\n` +
    `- Worksheet (3 levels) — cetak atau akses digital\n` +
    `- Lab Safety Sheet\n` +
    `- CER Template\n\n` +
    `---\n\n` +
    `*Generated by Physics Command Center — AI-Powered Teaching Platform*`
  )
}

function getParentMessage(topic: string, grade: number): string {
  const emoji = getEmoji(topic)
  return (
    `Assalamu'alaikum Wr. Wb.\n\n` +
    `Kepada Orang Tua/Wali Siswa Grade ${grade},\n\n` +
    `Kami sampaikan bahwa minggu ini di pelajaran Fisika, putra/putri Bapak/Ibu akan mempelajari *${topic}* ${emoji}.\n\n` +
    `Pembelajaran akan menggunakan model *Flipped Classroom*, di mana siswa menonton video dan mengerjakan guided notes SEBELUM datang ke kelas. Kami mohon bantuan Bapak/Ibu untuk:\n\n` +
    `1️⃣ Mengingatkan putra/putri untuk menonton video pre-class yang sudah tersedia di LMS\n` +
    `2️⃣ Memastikan mereka mengerjakan Entry Ticket Quiz sebelum jam pelajaran\n` +
    `3️⃣ Mendukung proses belajar mereka di rumah — tanyakan apa yang mereka pelajari!\n\n` +
    `Untuk informasi lebih lanjut, silakan cek LMS atau menghubungi guru mata pelajaran.\n\n` +
    `Wassalamu'alaikum Wr. Wb.\n\n` +
    `Salam hangat,\n` +
    `Tim Fisika SHB Modernhill`
  )
}

export async function generateBroadcast(input: AgentInput): Promise<BroadcastMessage> {
  const deadline = `Deadline: Jumat, minggu ini pukul 23:59 WIB`

  return {
    wa_message: getWaBody(input.topic, input.grade, input.week_number),
    lms_post: {
      title: getLmsTitle(input.topic, input.week_number),
      body: getLmsBody(input.topic, input.grade),
      attachments: [
        { name: `Worksheet_${input.topic.replace(/\s+/g, "_")}_G${input.grade}_W${input.week_number}.pdf`, url: "#" },
        { name: `CER_Template_G${input.grade}.pdf`, url: "#" },
        { name: `Lab_Safety_Sheet.pdf`, url: "#" }
      ],
      deadline
    },
    parent_message: getParentMessage(input.topic, input.grade)
  }
}
